# Problem statement
Avi Mehenwal avi.mehenwal@gmai.com

A automation script to make a booking on goibibo from _Bangalore_ to _Mumbai_.

* Travel date : tomorrow
* Return Date : tomorrow + 2
* Select the earliest flights on both days
* Asserts
** Proceed to pay
** Total amount

---

### Requirnments

* Python 3.6 or above
----
python -V
----
* http://robotframework.org/[Robot Framework] selenium layer for browser automation.
* Docker images for chrome and firefox
.Docker commands
----
# fetch docker image
docker pull selenium/standalone-chrome-debug

# Run docker image and expose ports
docker run -d -p 4444:4444 -p 5900:5900 -v /dev/shm:/dev/shm selenium/standalone-chrome-debug:3.12.0-americium

# Connect via vnc (if debug required)
vncviewer localhost:5900
----
* chromedrive and geckodriver (if not using docker)

### Steps to run the project
Setup python virtual environment
----
python3 -m venv ENV-NAME
source path/to/virtualenv/bin/activate
pip install robotframework
pip install robotframework-seleniumlibrary
----
Navigate to project directory
----
cd path/to/projectdir
----
Run `robot goibibo_test.robot`
----
robot src/goibibo_test.robot
----
Open `results.html` or `log.html` files  generated in the current directory to view test report


#### Challenges
* xpaths to move up/down in hierarchy
* css selectors for targetted selection, Eg: datepicker columns
* Clicking elements not in visible view
* Site behaves differenctly in chrome and firefox browsers. Search results page varies
* In chrome elements move but in firefox they are clickable and fixed
* Overlapping items, datepicker values under ad-banner]


### Open Issues
* Pass dynamic values to datepicker
* Figure out why css selector is not working when xpath is!


#### Changelog
* datepicker selection based on text field and not by position
* Modularize
