# Problem statement
Avi Mehenwal avi.mehenwal@gmai.com

A automation script to make a booking on goibibo from _Bangalore_ to _Mumbai_.

* Travel date : tomorrow
* Return Date : tomorrow + 2
* Select the earliest flights on both days
* Asserts
** Proceed to pay
** Total amount

---

### How to view this project
1. All aumomated test scripts and reports are inside `src` directory
2. All manual test-reports, screenshots and demos are inside `docs` dir
3. Instructions on how to run locally are inside `README`. Use browser https://chrome.google.com/webstore/detail/asciidoctorjs-live-previe/iaalpfgpbocpdfblpnhhgllgbdbchmia?hl=en[Asciidoctor chrome plugin] to open README file for rich formatted text view


### Requirnments

* Python 3.6 or above
----
python -V

# setting up virtual environment
python3 -m venv springboard

# activating python virtual environment
source springboard/bin/activate
----
* http://robotframework.org/[Robot Framework] selenium layer for browser automation.
----
# installing robotframework and selenium bindings
pip install robotframework
pip install --upgrade robotframework-seleniumlibrary
----
* Docker images for chrome and firefox
.Docker commands
----
# fetch docker image
docker pull selenium/standalone-chrome-debug

# Run docker image and expose ports
docker run -d -p 4444:4444 -p 5900:5900 -v /dev/shm:/dev/shm selenium/standalone-chrome-debug:3.12.0-americium

# Connect via vnc (if debug required)
vncviewer localhost:5900
----
* chromedrive and geckodriver (if not using docker)


### Steps to run the project
Setup python virtual environment
----
python3 -m venv ENV-NAME
source path/to/virtualenv/bin/activate
pip install robotframework
pip install robotframework-seleniumlibrary
----
Navigate to project directory
----
cd path/to/projectdir
----
Make sure `selenium/standalone-chrome-debug` docker container is up and running and you are connected via VNC.

Run `robot goibibo_test.robot`
----
robot src/goibibo_test.robot
----
Open `results.html` or `log.html` files  generated in the current directory to view test report


#### Challenges
* xpaths to move up/down in hierarchy
* css selectors for targetted selection, Eg: datepicker columns
* Clicking elements not in visible view
* Site behaves differenctly in chrome and firefox browsers. Search results page varies
* In chrome elements move but in firefox they are clickable and fixed
* Overlapping items, datepicker values under ad-banner]


### Open Issues
* Figure out why css selector is not working when xpath is!

### Manual test report at
link:docs/index.html[Link to Manual test-report]

#### Changelog
* datepicker selection based on text field and not by position
* Modularize

# END
